version: '3'

services:

  traefik:
    image: traefik:v1.7.3
    command: --docker
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik/traefik.toml:/traefik.toml
      - ${PWD}/traefik/acme.json:/acme.json
    labels:
      - "traefik.frontend.rule=Host:traefik.eoastest5.xyz"
      - "traefik.port=8080"
    container_name: traefik
    restart: always

networks:
  proxy:
    external: true