debug = true
logLevel = "DEBUG" #DEBUG, INFO, WARN, ERROR, FATAL
defaultEntryPoints = ["http"]

sendAnonymousUsage = true

[docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
  watch = true
  domain = "localhost"


#Enable retry sending a request if the network error
[retry]

# enabling api is not absolutely necessary, it is needed only if you need dashboard.
[api]
dashboard = true

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.authenticate]
  address = ":8081"
  [entryPoints.authenticate.auth.basic]
  users = ["phil:$apr1$T1qLNvVo$jVm15GW/mDPSa/nzxCil/1"]

[file]
filename = "rules.toml"
watch = true



